##
# This file is part of the Sylakim package.
#
# (c) Sylake
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
##

parameters:
    sylake_sylakim.normalizer.attribute.class: Sylake\Bundle\SylakimBundle\Normalizer\AttributeNormalizer
    sylake_sylakim.normalizer.category.class: Sylake\Bundle\SylakimBundle\Normalizer\CategoryNormalizer
    sylake_sylakim.normalizer.family.class: Sylake\Bundle\SylakimBundle\Normalizer\FamilyNormalizer

services:
    sylake_sylakim.normalizer.attribute:
        class: %sylake_sylakim.normalizer.attribute.class%
        arguments:
            - [ json, xml ]
        tags:
            - { name: sylake_sylakim.serializer.normalizer }

    sylake_sylakim.normalizer.category:
        class: %sylake_sylakim.normalizer.category.class%
        arguments:
            - [ json, xml ]
        tags:
            - { name: sylake_sylakim.serializer.normalizer }

    sylake_sylakim.normalizer.family:
        class: %sylake_sylakim.normalizer.family.class%
        arguments:
            - [ json, xml ]
        tags:
            - { name: sylake_sylakim.serializer.normalizer }
