##
# This file is part of the Sylakim package.
#
# (c) Sylake
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
##

parameters:
    sylake_sylakim.processor.entity_to_array.class: Sylake\Bundle\SylakimBundle\Processor\EntityToArrayProcessor

services:
    sylake_sylakim.processor.entity_to_array:
        class: %sylake_sylakim.processor.entity_to_array.class%
        arguments:
            - '@sylake_sylakim.serializer'
