##
# This file is part of the Sylakim package.
#
# (c) Sylake
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
##

parameters:
    sylake_sylakim.writer.sylius.class: Sylake\Bundle\SylakimBundle\Writer\SyliusWriter

services:
    sylake_sylakim.writer.sylius:
        class: %sylake_sylakim.writer.sylius.class%
